### ISSUE TITLE
ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.schedule_sdb fails

### ISSUE THREAD

**Issue by Reynders1** [aneeshd/schedule_state#188]
## Configuration

```- platform: schedule_state
  name: Schedule SdB
  refresh: "6:00:00"
  default_state: default
  icon: mdi:calendar-check
  error_icon: mdi:calendar-alert
  minutes_to_refresh_on_error: 5
  events:
    - start: "0:00"
      end: "8:00"
      state: night
      icon: mdi:weather-night
    - start: "8:00"
      end: "8:30"
      state: boost
      icon: mdi:thermometer-chevron-up
    - start: "8:30"
      end: "23:00"
      state: day
      icon: mdi:sun-thermometer
    - start: "23:00"
      state: night
      icon: mdi:weather-night
    - state: away
      condition:
        - condition: state
          entity_id: zone.home
          state: 0'
    - state: summer
      condition:
        - condition: state
          entity_id: input_boolean.mode_ete
          state: 'on'

```

## Describe the bug
This error message appears about every 30 seconds.
In addition, the sensor.schedule_sdb goes unavailable.
This is the case for all sensor.schedule_xxx

## Debug log

```2023-12-16 14:59:25.380 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.schedule_sdb fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 698, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 959, in async_device_update
    await self.async_update()
  File "/config/custom_components/schedule_state/sensor.py", line 479, in async_update
    await self.data.update()
  File "/config/custom_components/schedule_state/sensor.py", line 948, in update
    self.overrides = [o for o in self.overrides if dt.as_local(o["expires"]) > now]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/schedule_state/sensor.py", line 948, in 
    self.overrides = [o for o in self.overrides if dt.as_local(o["expires"]) > now]
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/dt.py", line 141, in as_local
    if dattim.tzinfo == DEFAULT_TIME_ZONE:
       ^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'


```

**Comment by aneeshd** [comment]
@Reynders1 can you explain a bit more how/when this happens? Did you recently upgrade and it's a new problem? Did you use some overrides? Does it happen after you restart? etc

**Comment by Reynders1** [comment]
Hi @aneeshd,
I updated recently (in fact after you fixed the "Service_Working but with bug report #155"). Installed version is 0.19.2. It might well be since this update that I get the error messages, but cannot confirm it. It is anyway recent.
I use overrides in a scripts which runs when I manually change the predefined temperature of a TRV. It used to work fine for months! Here is an extract of the code used:
```
sequence:
    - variables:
        override: "{{states('input_number.override_duration_'+called_from_mode) | int}}"

# force schedule mode
    - service: schedule_state.set_override
      data:
        state: '{{ called_from_mode }}'
        duration: '{{ override }}'
      target:
        entity_id: 'sensor.schedule_{{ called_from_room }}'
````
The error happens as soon as HA has started.

**Comment by aneeshd** [comment]
OK, thanks. I’ll try to figure out what’s going on…

**Comment by cwrau** [comment]
Same thing is happening for me since I updated from 0.19.1 to 0.19.2 today

Exact same log

**Comment by aneeshd** [comment]
I managed to reproduce it. Hopefully I'll find a fix soon

**Comment by aneeshd** [comment]
I think it's fixed - let me know

**Comment by Reynders1** [comment]
@aneeshd 
The error no longer shows up... It seems you fixed it indeed!

Many thanks for your great support.

Enjoy the end of year break.

**Comment by aneeshd** [comment]
cool
